spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample_users
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      encoding: utf-8
  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: none
  thymeleaf:
    prefix: file:src/main/resources/templates/